!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE SHALLOW_WATER_STEP_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of rhs_sw in reverse (adjoint) mode:
!   gradient     of useful results: rhs_u rhs_v rhs_eta
!   with respect to varying inputs: rhs_u rhs_v un rhs_eta vn etan
!   RW status of diff variables: rhs_u:in-out rhs_v:in-out un:out
!                rhs_eta:in-out vn:out etan:out
  SUBROUTINE RHS_SW_B(unb, vnb, etanb, rhs_ub, rhs_vb, rhs_etab, nx, ny, g, h, coriolis, dx, dy)
    IMPLICIT NONE
    INTEGER :: nx, ny
    REAL, DIMENSION(nx+1, 0:ny+1) :: unb
    REAL, DIMENSION(0:nx+1, ny+1) :: vnb
    REAL, DIMENSION(0:nx+1, 0:ny+1) :: etanb
    REAL, DIMENSION(nx+1, 0:ny+1) :: rhs_ub
    REAL, DIMENSION(0:nx+1, ny+1) :: rhs_vb
    REAL, DIMENSION(0:nx+1, 0:ny+1) :: rhs_etab
    REAL :: dx, dy
    REAL :: g, h, coriolis
    INTEGER :: i, j
    REAL :: tempb
    REAL :: tempb0

    real, parameter :: beta = 0.00

    unb = 0.0
    vnb = 0.0
    DO j=ny,1,-1
      DO i=nx,1,-1
        tempb0 = -(h*rhs_etab(i, j)/dx)
        tempb = -(h*rhs_etab(i, j)/dy)
        rhs_etab(i, j) = 0.0
        vnb(i, j+1) = vnb(i, j+1) + tempb
        vnb(i, j) = vnb(i, j) - tempb
        unb(i+1, j) = unb(i+1, j) + tempb0
        unb(i, j) = unb(i, j) - tempb0
      END DO
    END DO
    etanb = 0.0
    DO j=ny,2,-1
      DO i=nx,1,-1
        tempb0 = -(g*rhs_vb(i, j)/dy)
        tempb = -((coriolis+j*beta)*0.25*rhs_vb(i, j))
        rhs_vb(i, j) = 0.0
        unb(i, j-1) = unb(i, j-1) + tempb
        unb(i+1, j-1) = unb(i+1, j-1) + tempb
        unb(i, j) = unb(i, j) + tempb
        unb(i+1, j) = unb(i+1, j) + tempb
        etanb(i, j) = etanb(i, j) + tempb0
        etanb(i, j-1) = etanb(i, j-1) - tempb0
      END DO
    END DO
    DO j=ny,1,-1
      DO i=nx,2,-1
        tempb = (coriolis+j*beta)*0.25*rhs_ub(i, j)
        tempb0 = -(g*rhs_ub(i, j)/dx)
        rhs_ub(i, j) = 0.0
        etanb(i, j) = etanb(i, j) + tempb0
        etanb(i-1, j) = etanb(i-1, j) - tempb0
        vnb(i-1, j) = vnb(i-1, j) + tempb
        vnb(i, j) = vnb(i, j) + tempb
        vnb(i-1, j+1) = vnb(i-1, j+1) + tempb
        vnb(i, j+1) = vnb(i, j+1) + tempb
      END DO
    END DO
  END SUBROUTINE RHS_SW_B

  SUBROUTINE RHS_SW(un, vn, etan, rhs_u, rhs_v, rhs_eta, nx, ny, g, h, &
&   coriolis, dx, dy)
    IMPLICIT NONE
    INTEGER :: nx, ny
    REAL, DIMENSION(nx+1, 0:ny+1) :: un
    REAL, DIMENSION(0:nx+1, ny+1) :: vn
    REAL, DIMENSION(0:nx+1, 0:ny+1) :: etan
    REAL, DIMENSION(nx+1, 0:ny+1) :: rhs_u
    REAL, DIMENSION(0:nx+1, ny+1) :: rhs_v
    REAL, DIMENSION(0:nx+1, 0:ny+1) :: rhs_eta
    REAL :: dx, dy
    REAL :: g, h, coriolis
    INTEGER :: i, j

    real, parameter :: beta = 0.00

    DO j=1,ny
      DO i=2,nx
        rhs_u(i, j) = -(g*(etan(i, j)-etan(i-1, j))/dx) + (coriolis+j*beta)*0.25*&
&         (vn(i-1, j)+vn(i, j)+vn(i-1, j+1)+vn(i, j+1))
      END DO
    END DO
    DO j=2,ny
      DO i=1,nx
        rhs_v(i, j) = -(g*(etan(i, j)-etan(i, j-1))/dy) - (coriolis+j*beta)*0.25*&
&         (un(i, j-1)+un(i+1, j-1)+un(i, j)+un(i+1, j))
      END DO
    END DO
    DO j=1,ny
      DO i=1,nx
        rhs_eta(i, j) = -(h*(un(i+1, j)-un(i, j))/dx) - h*(vn(i, j+1)-vn&
&         (i, j))/dy
      END DO
    END DO
  END SUBROUTINE RHS_SW

END MODULE SHALLOW_WATER_STEP_DIFF
